### ISSUE TITLE
Error: Query.node field type must be Output Type but got: Node.

### ISSUE THREAD

**Issue by AchrafBn** [BlueEastCode/loopback-graphql-relay#20]
i get error in my console : 
`Error: Query.node field type must be Output Type but got: Node.`
`  at invariant (/Users/macbookpro/Documents/nour/node_modules/loopback-graphql-relay/node_modules/graphql/jsutils/invariant.js:19:11)`
`  at /Users/macbookpro/Documents/nour/node_modules/loopback-graphql-relay/node_modules/graphql/type/definition.js:337:29`
`at defineFieldMap (/Users/macbookpro/Documents/nour/node_modules/loopback-graphql-relay/node_modules/graphql/type/definition.js:328:14)`

the node version : v8.2.1
has anybody met this error?

**Comment by AchrafBn** [comment]
I solved the problem check https://github.com/relayjs/relay-examples/issues/25#issuecomment-321768114
